# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# before_script:
#   - composer self-update -q
#   - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
#   - if [ -z "$dependencies" ]; then composer install; fi;
#   - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
#   - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
#   - composer show -i

# command to run tests, e.g. python setup.py test
script: tox

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: fanglab
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: fanglab/mbin
    python: 2.7
